### ISSUE TITLE
2.0.0 fails when used with Homestead Remote PHP interpreter

### ISSUE THREAD

**Issue by jesperbjerke** [Roboroads/laravel-tinker#48]
**Bug description**
Since the last update, all tinker sessions fails with the following error:

```
zsh:cd:1: no such file or directory: /Users/jesperbjerke/Dropbox/www/homestead/xxx
Warning: require(/home/vagrant/vendor/autoload.php): failed to open stream: No such file or directory in Command line code on line 7
PHP Warning:  require(/home/vagrant/vendor/autoload.php): failed to open stream: No such file or directory in Command line code on line 7

Fatal error: require(): Failed opening required '/home/vagrant/vendor/autoload.php' (include_path='.:/usr/share/php') in Command line code on line 7
PHP Fatal error:  require(): Failed opening required '/home/vagrant/vendor/autoload.php' (include_path='.:/usr/share/php') in Command line code on line 7
```

I am using a remote PHP interpreter through Laravel Homestead. Everything worked perfectly before the last update.

**To Reproduce**
Setup a Remote PHP interpreter and run any type of code through tinker. Fails even with just `echo 'test';`

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.3.2
 - PHP Version: 7.4
 - OS: macOS 11.2.1
 - Laravel Tinker plugin version: 2.0.0
 - Interpreter Type: Remote (Laravel Homestead)
 - Laravel Version: 8.30.1
 - Tinker version: 2.6.1

**Comment by Roboroads** [comment]
Looks liek there is some weird stuff going on when using interpretation over ssh - I'm going to look into it when I get the time

**Comment by Roboroads** [comment]
@jesperbjerke Hasw this been solved by the last version?

**Comment by jesperbjerke** [comment]
@Roboroads Unfortunately the same problem still occurs on 2.2.0

**Comment by jesperbjerke** [comment]
Still an issue with 2.2.2

**Comment by jesperbjerke** [comment]
Yes, it's setup properly. It worked with exactly the same setup in version 1.x and stopped working in 2.x. 
But when I started poking around the path mappings I found the issue.

PHPStorm works fine and the other PHP tools I use work properly with current setup through remote interpreter (phpcs, phpstan etc etc). However I have project source code setup in Dropbox, witch creates a symlink called like "Dropbox (Personal)" which makes the path look something like `/Users/jesperbjerke/Dropbox (Personal)/www/`, and this seems to break it. I added a new path mapping with the absolute path and now it works.

**Comment by Roboroads** [comment]
I'm glad we got it sorted out 😊
